### PR TITLE
fix drag-and-drop in viewtree as well as site creation for SS 3.3+

### PR DESCRIPTION
**Pull request by xini**
not compatible with SS <3.3

### CODE REVIEW

**Comment by nyeholt** [comment]
Is there something in particular that doesn't work in 3.2 for site creation using a form? I'm a bit hesitant to rely on a direct get request for site creation is all.

**Comment by xini** [comment]
I couldn't get it to work properly and adding a form in that button row broke the layout. So I opted for the simpler option...

**Comment by xini** [comment]
It's SS 3.3 and up though. 3.2 should still work.

**Comment by xini** [comment]
Hi Marcus,
How do you want me to proceed here? Do you have a better solution?
Cheers, Flo

**Comment by xini** [comment]
Hi @nyeholt 
I have amended the PR to use the form as requested. also rebased.
Cheers, Flo

**Comment by nyeholt** [comment]
Sorry, I missed the notification when it came through - thanks heaps for this!

**Comment by xini** [comment]
no problem. can you please tag a release with this? cheers

**Comment by Codesesh** [comment]
Hey guys, can we get this released ASAP, have a client site that really needs this implemented: https://github.com/silverstripe-australia/silverstripe-multisites/issues/70

**Comment by xini** [comment]
this is fixed and tagged as release 3.0.0

**Pull request merged**
